# Generated by Django 6.0.4 on 2026-04-15 19:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chofer',
            name='codigo_legacy',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='chofer',
            name='datos_legacy',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='chofer',
            name='origen_legacy',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='cliente',
            name='codigo_legacy',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='cliente',
            name='datos_legacy',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='cliente',
            name='origen_legacy',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='chofer',
            name='direccion',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='chofer',
            name='dni',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='chofer',
            name='patente',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='chofer',
            name='registro',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='chofer',
            name='seguro',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='chofer',
            name='telefono',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='chofer',
            name='vehiculo',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='direccion',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='telefono',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
        migrations.CreateModel(
            name='Viaje',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(blank=True, null=True)),
                ('origen', models.CharField(blank=True, max_length=255)),
                ('destino', models.CharField(blank=True, max_length=255)),
                ('importe', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('en_curso', 'En curso'), ('finalizado', 'Finalizado'), ('cancelado', 'Cancelado'), ('sin_estado', 'Sin estado')], default='sin_estado', max_length=20)),
                ('observaciones', models.TextField(blank=True)),
                ('codigo_legacy', models.CharField(max_length=50, unique=True)),
                ('cliente_codigo_legacy', models.CharField(blank=True, max_length=50)),
                ('chofer_codigo_legacy', models.CharField(blank=True, max_length=50)),
                ('origen_legacy', models.CharField(default='VIAJES.DBF', max_length=30)),
                ('datos_legacy', models.JSONField(blank=True, default=dict)),
                ('fecha_importacion', models.DateTimeField(auto_now_add=True)),
                ('chofer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='viajes', to='core.chofer')),
                ('cliente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='viajes', to='core.cliente')),
            ],
            options={
                'verbose_name': 'Viaje historico',
                'verbose_name_plural': 'Viajes historicos',
                'ordering': ['-fecha', '-id'],
            },
        ),
        migrations.CreateModel(
            name='Factura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=50)),
                ('fecha', models.DateField(blank=True, null=True)),
                ('importe_total', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('pagada', 'Pagada'), ('anulada', 'Anulada'), ('sin_estado', 'Sin estado')], default='sin_estado', max_length=20)),
                ('observaciones', models.TextField(blank=True)),
                ('codigo_legacy', models.CharField(max_length=50, unique=True)),
                ('cliente_codigo_legacy', models.CharField(blank=True, max_length=50)),
                ('viaje_codigo_legacy', models.CharField(blank=True, max_length=50)),
                ('origen_legacy', models.CharField(default='FACTURAC.DBF', max_length=30)),
                ('datos_legacy', models.JSONField(blank=True, default=dict)),
                ('fecha_importacion', models.DateTimeField(auto_now_add=True)),
                ('cliente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='facturas', to='core.cliente')),
                ('viaje', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='facturas', to='core.viaje')),
            ],
            options={
                'verbose_name': 'Factura historica',
                'verbose_name_plural': 'Facturas historicas',
                'ordering': ['-fecha', '-id'],
            },
        ),
        migrations.AddIndex(
            model_name='viaje',
            index=models.Index(fields=['fecha'], name='core_viaje_fecha_3b9579_idx'),
        ),
        migrations.AddIndex(
            model_name='viaje',
            index=models.Index(fields=['estado'], name='core_viaje_estado_de3380_idx'),
        ),
        migrations.AddIndex(
            model_name='viaje',
            index=models.Index(fields=['cliente'], name='core_viaje_cliente_0cc09d_idx'),
        ),
        migrations.AddIndex(
            model_name='viaje',
            index=models.Index(fields=['chofer'], name='core_viaje_chofer__4d8862_idx'),
        ),
        migrations.AddIndex(
            model_name='viaje',
            index=models.Index(fields=['codigo_legacy'], name='core_viaje_codigo__25bff5_idx'),
        ),
        migrations.AddIndex(
            model_name='factura',
            index=models.Index(fields=['fecha'], name='core_factur_fecha_f77064_idx'),
        ),
        migrations.AddIndex(
            model_name='factura',
            index=models.Index(fields=['estado'], name='core_factur_estado_741c71_idx'),
        ),
        migrations.AddIndex(
            model_name='factura',
            index=models.Index(fields=['cliente'], name='core_factur_cliente_f3f1d0_idx'),
        ),
        migrations.AddIndex(
            model_name='factura',
            index=models.Index(fields=['viaje'], name='core_factur_viaje_i_fa6842_idx'),
        ),
        migrations.AddIndex(
            model_name='factura',
            index=models.Index(fields=['codigo_legacy'], name='core_factur_codigo__e3dcea_idx'),
        ),
    ]
