# Generated by Django 6.0.4 on 2026-04-16 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_chofer_codigo_legacy_chofer_datos_legacy_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='flete',
            name='forma_de_pago',
            field=models.CharField(choices=[('efectivo', 'Efectivo'), ('cuenta_corriente', 'Cuenta corriente')], max_length=20, null=True),
        ),
    ]
