# Generated by Django 6.0.4 on 2026-04-16 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_flete_forma_de_pago'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cobro',
            name='metodo_pago',
            field=models.CharField(choices=[('efectivo', 'Efectivo'), ('cuenta_corriente', 'Cuenta corriente')], max_length=20),
        ),
    ]
