# Generated by Django 6.0.4 on 2026-04-16 01:23

from django.db import migrations, models


def sincronizar_pagado(apps, schema_editor):
    Flete = apps.get_model("core", "Flete")
    Cobro = apps.get_model("core", "Cobro")

    fletes_pagados = Cobro.objects.filter(estado="pagado").values_list("flete_id", flat=True)
    Flete.objects.filter(id__in=fletes_pagados).update(pagado=True)


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_cobro_metodo_pago'),
    ]

    operations = [
        migrations.AddField(
            model_name='flete',
            name='pagado',
            field=models.BooleanField(default=False),
        ),
        migrations.RunPython(sincronizar_pagado, migrations.RunPython.noop),
    ]
