# Generated by Django 6.0.4 on 2026-04-16 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_flete_pagado'),
    ]

    operations = [
        migrations.AddField(
            model_name='flete',
            name='fecha_hora_en_curso',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='flete',
            name='fecha_hora_finalizado',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
