# Generated by Django 6.0.4 on 2026-07-25 22:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChoferHistorico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_legacy', models.CharField(max_length=80, unique=True)),
                ('origen_legacy', models.CharField(blank=True, max_length=40)),
                ('datos_legacy', models.JSONField(blank=True, default=dict)),
                ('fecha_importacion', models.DateTimeField(auto_now_add=True)),
                ('nombre', models.CharField(max_length=150)),
                ('telefono', models.CharField(blank=True, max_length=40)),
                ('dni', models.CharField(blank=True, max_length=40)),
                ('registro', models.CharField(blank=True, max_length=80)),
                ('direccion', models.CharField(blank=True, max_length=255)),
                ('estado', models.CharField(blank=True, max_length=30)),
                ('vehiculo', models.CharField(blank=True, max_length=120)),
                ('patente', models.CharField(blank=True, max_length=40)),
                ('seguro', models.CharField(blank=True, max_length=120)),
                ('observaciones', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Chofer historico',
                'verbose_name_plural': 'Choferes historicos',
                'ordering': ['nombre', 'codigo_legacy'],
            },
        ),
        migrations.CreateModel(
            name='ClienteHistorico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_legacy', models.CharField(max_length=80, unique=True)),
                ('origen_legacy', models.CharField(blank=True, max_length=40)),
                ('datos_legacy', models.JSONField(blank=True, default=dict)),
                ('fecha_importacion', models.DateTimeField(auto_now_add=True)),
                ('nombre', models.CharField(max_length=150)),
                ('telefono', models.CharField(blank=True, max_length=40)),
                ('direccion', models.CharField(blank=True, max_length=255)),
                ('activo', models.BooleanField(default=True)),
                ('observaciones', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Cliente historico',
                'verbose_name_plural': 'Clientes historicos',
                'ordering': ['nombre', 'codigo_legacy'],
            },
        ),
        migrations.CreateModel(
            name='ReservaHistorica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_legacy', models.CharField(max_length=80, unique=True)),
                ('origen_legacy', models.CharField(blank=True, max_length=40)),
                ('datos_legacy', models.JSONField(blank=True, default=dict)),
                ('fecha_importacion', models.DateTimeField(auto_now_add=True)),
                ('cliente_codigo_legacy', models.CharField(blank=True, max_length=80)),
                ('chofer_codigo_legacy', models.CharField(blank=True, max_length=80)),
                ('fecha', models.DateField(blank=True, null=True)),
                ('hora', models.TimeField(blank=True, null=True)),
                ('origen', models.CharField(blank=True, max_length=255)),
                ('destino', models.CharField(blank=True, max_length=255)),
                ('importe', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('estado', models.CharField(choices=[('reserva', 'Reserva'), ('pendiente', 'Pendiente'), ('en_curso', 'En curso'), ('finalizado', 'Finalizado'), ('cancelado', 'Cancelado'), ('sin_estado', 'Sin estado')], default='reserva', max_length=20)),
                ('observaciones', models.TextField(blank=True)),
                ('chofer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reservas_historicas', to='importadores.choferhistorico')),
                ('cliente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reservas_historicas', to='importadores.clientehistorico')),
            ],
            options={
                'verbose_name': 'Reserva historica',
                'verbose_name_plural': 'Reservas historicas',
                'ordering': ['-fecha', '-hora', '-codigo_legacy'],
                'indexes': [models.Index(fields=['fecha'], name='importadore_fecha_4d09a3_idx'), models.Index(fields=['estado'], name='importadore_estado_b322ad_idx'), models.Index(fields=['codigo_legacy'], name='importadore_codigo__5f792a_idx')],
            },
        ),
        migrations.CreateModel(
            name='ViajeHistorico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_legacy', models.CharField(max_length=80, unique=True)),
                ('origen_legacy', models.CharField(blank=True, max_length=40)),
                ('datos_legacy', models.JSONField(blank=True, default=dict)),
                ('fecha_importacion', models.DateTimeField(auto_now_add=True)),
                ('cliente_codigo_legacy', models.CharField(blank=True, max_length=80)),
                ('chofer_codigo_legacy', models.CharField(blank=True, max_length=80)),
                ('fecha', models.DateField(blank=True, null=True)),
                ('hora', models.TimeField(blank=True, null=True)),
                ('origen', models.CharField(blank=True, max_length=255)),
                ('destino', models.CharField(blank=True, max_length=255)),
                ('importe', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('estado', models.CharField(choices=[('reserva', 'Reserva'), ('pendiente', 'Pendiente'), ('en_curso', 'En curso'), ('finalizado', 'Finalizado'), ('cancelado', 'Cancelado'), ('sin_estado', 'Sin estado')], default='sin_estado', max_length=20)),
                ('observaciones', models.TextField(blank=True)),
                ('chofer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='viajes_historicos', to='importadores.choferhistorico')),
                ('cliente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='viajes_historicos', to='importadores.clientehistorico')),
            ],
            options={
                'verbose_name': 'Viaje historico',
                'verbose_name_plural': 'Viajes historicos',
                'ordering': ['-fecha', '-hora', '-codigo_legacy'],
                'indexes': [models.Index(fields=['fecha'], name='importadore_fecha_4e3f3b_idx'), models.Index(fields=['estado'], name='importadore_estado_1e0228_idx'), models.Index(fields=['codigo_legacy'], name='importadore_codigo__8541a5_idx')],
            },
        ),
    ]
