# Generated by Django 6.0.4 on 2026-07-26 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('importadores', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='choferhistorico',
            name='descripcion_vehiculo',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='choferhistorico',
            name='motivo_clasificacion',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='choferhistorico',
            name='patente_legacy',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name='choferhistorico',
            name='tipo_probable',
            field=models.CharField(choices=[('flete_utilitario', 'Flete-utilitario'), ('auto_remis', 'Auto-remis'), ('desconocido', 'Desconocido')], default='desconocido', max_length=20),
        ),
        migrations.AddField(
            model_name='choferhistorico',
            name='tipo_vehiculo_legacy',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='reservahistorica',
            name='motivo_clasificacion',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='reservahistorica',
            name='tipo_probable',
            field=models.CharField(choices=[('flete_utilitario', 'Flete-utilitario'), ('auto_remis', 'Auto-remis'), ('desconocido', 'Desconocido')], default='desconocido', max_length=20),
        ),
        migrations.AddField(
            model_name='reservahistorica',
            name='usuario_carga',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='reservahistorica',
            name='vehiculo_chofer',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='viajehistorico',
            name='motivo_clasificacion',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='viajehistorico',
            name='tipo_probable',
            field=models.CharField(choices=[('flete_utilitario', 'Flete-utilitario'), ('auto_remis', 'Auto-remis'), ('desconocido', 'Desconocido')], default='desconocido', max_length=20),
        ),
        migrations.AddField(
            model_name='viajehistorico',
            name='usuario_carga',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='viajehistorico',
            name='vehiculo_chofer',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
